### ISSUE TITLE
UX: Include bundled support status somewhere on dashboard

### ISSUE THREAD

**Issue by ankush** [frappe/press#1017]
![image](https://github.com/frappe/press/assets/9079960/8c5a83d7-d553-43b7-92b0-50003a340e8a)

**Comment by BreadGenie** [comment]
resolved in 8ef924c885d3dd7f65d2fb7191a46a453df59d28


![Image](https://github.com/frappe/press/assets/63963181/e842a4f4-658a-45d0-85a7-755543387380)
