### ISSUE TITLE
feat:Option to select the version for each app in Frappe Cloud

### ISSUE THREAD

**Issue by IshwaryaM3** [frappe/press#1024]
Hi,

We need a feature in Frappe Cloud to select a particular version for each core apps. Currently we don't have a option to select versions and by default the latest version changes are getting deployed.

We are upgrading versions and testing in our TEST environment but the same version we are not able to deploy it in Frappe Cloud. Since the latest version changes gets deployed we are having multiple core issues in Production.

Kindly find the screenshots for reference.

![Screenshot from 2023-09-04 15-50-50](https://github.com/frappe/press/assets/62096194/88cbc111-9ff4-4196-9378-2e4298726c98)

Thanks!

**Comment by Sagarikanaik96** [comment]
Yes, having this feature added would help to ease the deployment process.
