### ISSUE TITLE
Site filter not working as expected

### ISSUE THREAD

**Issue by michellealva** [frappe/press#1039]
Either don't show archived sites at all or show these sites under "All".

If I use the Trial filter, I can see archived sites.

![IMAGE 2023-09-20 11_20_43](https://github.com/frappe/press/assets/50285544/4f3bfb38-a95c-4939-8b28-e999c0b5d88a)

These sites are not visible under All.

![IMAGE 2023-09-20 11_22_04](https://github.com/frappe/press/assets/50285544/3ab6fe55-d148-4e0c-9b29-b7a639ba76ef)

**Comment by rutwikhdev** [comment]
https://github.com/frappe/press/commit/995047361d8286e1f49946e683e2340baf6ad6b8
