### ISSUE TITLE
Cannot install app from marketplace

### ISSUE THREAD

**Issue by michellealva** [frappe/press#1040]
Site is available. I do not see it, and I get this error.

![IMAGE 2023-09-20 12:30:03](https://github.com/frappe/press/assets/50285544/2db8a4f8-9adc-493f-9923-e4c680f95eed)

FYI - I went to https://frappecloud.com/marketplace/apps/india_compliance and clicked on the Install now button.

**Comment by rutwikhdev** [comment]
https://github.com/frappe/press/commit/52271e8e3d999a4ab7e158d39b695c8289425075
