### ISSUE TITLE
Invoice not available from dashboard

### ISSUE THREAD

**Issue by michellealva** [frappe/press#1043]
The link to the old invoices under Billing > Invoice lands me on a broken page. The invoice exists in the system though.

<img width="1494" alt="Screenshot 2023-09-20 at 2 47 47 PM" src="https://github.com/frappe/press/assets/50285544/2be6f5b6-cdb1-425e-91fd-ba24a89bb110">

**Comment by rutwikhdev** [comment]
https://github.com/frappe/press/commit/1032aaf400676da10d77d7c8fc13339dcb4b4766
