### ISSUE TITLE
Team/permission ux issues

### ISSUE THREAD

**Issue by ankush** [frappe/press#1060]
![image](https://github.com/frappe/frappe/assets/9079960/d8194546-53e3-4920-bcc5-762b69859db7)

This dialogue gets stuck for 20-30 seconds with no feedback to user. Add some loading state? Or better yet, send it from background.

**Comment by ankush** [comment]
Copy can be better here, this is invitation to join a team right? so it should be diff for existing user of FC vs new user on FC. 

![image](https://github.com/frappe/press/assets/9079960/4b2103a1-c3cf-4a10-84a2-2d6a1ee37c98)

**Comment by ankush** [comment]
![image](https://github.com/frappe/press/assets/9079960/281e13bf-2f60-4a43-9ec0-cfc3c0b3999a)


No auto-complete? I don't know what permissions are there to enable/disable :grimacing:

**Comment by ankush** [comment]
Same user can have perm via user's perm or groups perm... how is this resolved? 

There's should be clear way of resolution. 

IMO group should be base perm and user can be applied on top of it, if it' configured. 

Right now this seems hard to debug if someone has issues with permissions.

**Comment by ankush** [comment]
![image](https://github.com/frappe/press/assets/9079960/705ad947-a878-4720-9fdd-fd65b8f872f0)


We need more actions :grimacing: 

- destructive actions - Deactivate/Drop site/DB reset
- Bench SSH access
- Biling/change of plans - This should maybe completely restricted to billing mangers in team. 
- View logs of any kind
- add/remove apps
- Download backups

**Comment by rutwikhdev** [comment]
> this whitespace seems unnecessary
> 
> ![image](https://user-images.githubusercontent.com/9079960/270335951-99f82167-faa1-4f6e-bf28-b64f994e97be.png)

This is default frappe-ui padding 🗿 Added a placeholder text so it doesn't look empty.

**Comment by rutwikhdev** [comment]
https://github.com/frappe/frappe-ui/pull/101
https://github.com/frappe/press/pull/1062
