### ISSUE TITLE
sites page on large public benches doesn't load

### ISSUE THREAD

**Issue by ankush** [frappe/press#1069]
earlier we only had bench instances + count so the query was probably faster. anyway, this still feels like some slow code causing it.

Example: https://frappecloud.com/dashboard/benches/bench-5503/sites

**Comment by BreadGenie** [comment]
the culprit is https://github.com/frappe/press/blob/36523db7add55d1fd71b16b60482abab0f7952b3/press/api/bench.py#L489-L500

The number of sites is 2086 hence the low speed

ig we will have to rethink the bench site screen

**Comment by ankush** [comment]
@BreadGenie for perf problem: unroll the loop and query for all sites at once using `IN` query :grimacing:
