### ISSUE TITLE
Marketplace App Web page description formatting broken

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/press#1114]
The markdown is not being rendered properly: 

<img width="1695" alt="CleanShot 2023-10-19 at 12 09 54@2x" src="https://github.com/frappe/press/assets/34810212/c21840c9-c54e-4592-8ba6-76c352262701">

Has been broken since the past few days...

**Comment by BreadGenie** [comment]
This was fixed in 4e890c9 and further refined in #1094 

### Chrome
![image](https://github.com/frappe/press/assets/63963181/52162ff0-35f0-4d3e-b2f1-058e9ac62c37)

### Firefox
![image](https://github.com/frappe/press/assets/63963181/6ff9330c-0cd7-4e8f-b705-21c07c47321c)

**Comment by NagariaHussain** [comment]
Basically it's cached (the style sheet file for marketplace) at Nginx level sometime, but disabling cache and reloading worked.
