### ISSUE TITLE
Other services for mail

### ISSUE THREAD

**Issue by saullo** [frappe/press#1121]
Currently the only available mail service is Mail Gun, add ability to use Amazon Work Mail, Gmail, or other services.

**Comment by rutwikhdev** [comment]
Are you talking about [email_delivery_service](https://frappecloud.com/marketplace/apps/email_delivery_service) app on marketplace?
This app works with Frappe Cloud only and is not mandatory to be used. If you want to setup your own email service in site you can check [this](https://docs.erpnext.com/docs/user/manual/en/email) out
