### ISSUE TITLE
feat : restrict access to Apps, Billing Section

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/press#1124]
It is important to restrict access to Apps, Billing Section to a specific group / user.

Ticket #5004

<img width="271" alt="Pasted Graphic 12" src="https://github.com/frappe/press/assets/4900815/4a55f8e2-d9fc-4066-8370-7899e6f15b1e">

**Comment by ankush** [comment]
@rutwikhdev / @BreadGenie this should be done via new granular permissions feature
