### ISSUE TITLE
Payment mode should be obvious

### ISSUE THREAD

**Issue by balamurali27** [frappe/press#1142]
![image](https://github.com/frappe/press/assets/25403045/437abe38-c579-4364-ba54-cb12bd5bc85e)

Above should never happen? Especially if they've added either card or credits
Ref: tickets/#5381

**Comment by rutwikhdev** [comment]
Fix: https://github.com/frappe/press/commit/71b209c91de763cdb9e6b36c63c53d5f3dc7c78b I don't see any other place this could've happened.
