### ISSUE TITLE
feat : restrict access to create new bench/sites and Apps Section

### ISSUE THREAD

**Issue by ashish-greycube** [frappe/press#1143]
In context to https://github.com/frappe/press/issues/1124

Even with granular permission, following happens
[1]Actual: create new bench / site is possible
![image](https://github.com/frappe/press/assets/29812965/8e17416e-1b09-432b-a561-c9212c0a6627)
![image](https://github.com/frappe/press/assets/29812965/2a07348a-be6f-41f6-8c8d-1819a57f9b16)
**Expected : create new bench/site should not be given to team members**
[2] Actual : App option is visible, also payouts tab shows details
![image](https://github.com/frappe/press/assets/29812965/655a9f0f-186e-4c86-8a23-ff1ab014245d)
**Expected : entire app option should not be visible**

**Comment by ashish-greycube** [comment]
@rutwikhdev , can this be done?

**Comment by BreadGenie** [comment]
fixed in https://github.com/frappe/press/pull/1793
