### ISSUE TITLE
No unread notifs but can see 3 unread

### ISSUE THREAD

**Issue by michellealva** [frappe/press#1172]
![telegram-cloud-photo-size-5-6244508675016341349-y](https://github.com/frappe/press/assets/50285544/7042c595-c1c0-470a-bb1c-32afd57fc3ed)

happens when impersonating a different team from desk

**Comment by BreadGenie** [comment]
https://github.com/frappe/press/commit/3bb5abba9eeaab5543279ff85def593f0e21a4bb reverted as impersonating got broken
this will be fixed in dashboard 2
