### ISSUE TITLE
Deadlock issue while finalizing invoice

### ISSUE THREAD

**Issue by michellealva** [frappe/press#1192]

**Comment by michellealva** [comment]
![Image](https://github.com/frappe/press/assets/50285544/b627804a-12f5-472e-9f61-30fb48bca343)

**Comment by rutwikhdev** [comment]
This looks like a problem where the document is edited from two different sources. @michellealva Could you add any links you have of recent invoices here. 

I can't grep for it like [this](https://frappecloud.com/app/invoice?_comments=%5B%22like%22%2C%22%25refresh%25%22%5D). 

On the deadlock side it [looks](https://frappecloud.com/app/scheduled-job-log?scheduled_job_type=invoice.finalize_draft_invoices) like we are pretty good.

**Comment by ankush** [comment]
https://frappecloud.com/app/comment?reference_doctype=Invoice&content=%5B%22like%22%2C%22%25refresh%25%22%5D 

@rutwikhdev

**Comment by rutwikhdev** [comment]
Yeah ig this happens sometime because the job runs along with other invoice jobs as 12:00 am.  All the invoices in the comments seem to be finalized. Closing for now.
