### ISSUE TITLE
pick nearest region in SaaS signups 

### ISSUE THREAD

**Issue by ankush** [frappe/press#1196]
This came up during some discussion about performance where we are trying to optimize response times by few ms but if in the end network latency is just so high it makes no noticable difference to user.

Afaik most of our signups go to Frankfurt cluster while most of our users are from India.

A very simple optimization to make sites feel faster is to host them near end user. E.g typical latency to paris can be 200ms while mumbai server would be 30-50ms. An easy 75% drop.

Note: you'll have to modify whatever heuristics are there for load balancing if you implement this.

**Comment by BreadGenie** [comment]
fixed in https://github.com/frappe/press/commit/03ad8da26d41aa58d1b76deecdc1b214fa327b3c
