### ISSUE TITLE
Allow configuring environment variables from dashboard UI

### ISSUE THREAD

**Issue by ankush** [frappe/press#1212]
- Just like site config, envvars should be configurable here.
- There should be system for setting private env variable not visible on desk but visible on desk (like blacklisted config keys)

![image](https://github.com/frappe/press/assets/9079960/0d0e169f-0b29-4714-9e0d-9184cd35e09e)

**Comment by tanmoysrt** [comment]
Hi @ankush I like to work on this feature.

**Comment by BreadGenie** [comment]
@tanmoysrt if you're giving it a shot, try it for dashboard beta

**Comment by tanmoysrt** [comment]
> @tanmoysrt if you're giving it a shot, try it for dashboard beta

Do I need to just update the press locally for dashboard beta? 

Or there are any other steps?

**Comment by BreadGenie** [comment]
You can comment the line
https://github.com/frappe/press/blob/3769c63c53facda7683aaa30e1d339b4c8718b1e/dashboard/index.html#L31

and uncomment
https://github.com/frappe/press/blob/3769c63c53facda7683aaa30e1d339b4c8718b1e/dashboard/index.html#L32

to access dashboard beta

visit <sitename>/dashboard-beta

**Comment by tanmoysrt** [comment]
> You can pull latest changes and then comment the line
> 
> https://github.com/frappe/press/blob/3769c63c53facda7683aaa30e1d339b4c8718b1e/dashboard/index.html#L31
> 
> and uncomment
> 
> https://github.com/frappe/press/blob/3769c63c53facda7683aaa30e1d339b4c8718b1e/dashboard/index.html#L32
> 
> to access dashboard beta
> 
> visit `<sitename>/dashboard-beta`

ok! thanks

**Comment by tanmoysrt** [comment]
Just want to clarify one thing -

As per current scenario, if we update common site config, it doesn't going to update common site config for existing running benches (unlike site config). If we deploy a new bench / re-deploy the bench under the `Release Group`, then the new changes take effect. Is it correct or am I missing something ?

For environment variables also, will it update the env variables for running bench with `Agent Job` or will have same behaviour like common site config ?
