### ISSUE TITLE
Bench build error

### ISSUE THREAD

**Issue by ur-uw** [frappe/press#1220]
Bench Version: 5.19.0
Node Version: 16.15.1 or v20.5.1
Frappe Version: 14 and 15
Python Version: 3.10.11
Yarn Version: 1.22.21
OS: Ubuntu Server 22.04

frappe@cloud:~/frappe-cloud/apps/press$ bench build
Assets for Release v15.3.0 don't exist
✔ Application Assets Linked                                                                                                            

yarn run v1.22.21
$ node esbuild --production --run-build-command
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
File                                                        Size

frappe/dist/js/
├─ bootstrap-4-web.bundle.FOZOVELL.js                       1.73 Kb
├─ controls.bundle.PCNEWZXG.js                              1232.01 Kb
├─ data_import_tools.bundle.VIC3357T.js                     126.33 Kb
├─ desk.bundle.ICKVR6H5.js                                  1081.66 Kb
├─ dialog.bundle.LQ6ZJXVY.js                                56.66 Kb
├─ form.bundle.XCHBKJIW.js                                  166.50 Kb
├─ frappe-web.bundle.VKJCYSFT.js                            827.14 Kb
├─ libs.bundle.TIV7ZGVY.js                                  556.25 Kb
├─ list.bundle.FXQOKJ2D.js                                  192.46 Kb
├─ logtypes.bundle.EKN7LWKW.js                              0.73 Kb
├─ onboarding_tours.bundle.P2YWPPES.js                      7.58 Kb
├─ report.bundle.AIL7XWQC.js                                195.53 Kb
├─ telemetry.bundle.4CY3TWEX.js                             2.56 Kb
├─ user_profile_controller.bundle.ZJ6AYZ5P.js               11.96 Kb
├─ video_player.bundle.DUYYLSFO.js                          120.67 Kb
├─ web_form.bundle.EZXAPYO3.js                              1423.03 Kb
├─ form_builder.bundle.SHPR7AQO.js                          793.43 Kb
├─ form_builder.bundle.DKFU37FO.css                         23.02 Kb
├─ print_format_builder.bundle.SNEIY6UD.js                  682.54 Kb
├─ print_format_builder.bundle.HBNAX4DY.css                 5.54 Kb
├─ workflow_builder.bundle.LBP6SMUC.js                      351.75 Kb
├─ workflow_builder.bundle.WJGTYRYG.css                     11.02 Kb
├─ build_events.bundle.NROU6VPW.js                          104.77 Kb
├─ build_events.bundle.DBSSZ7MS.css                         1.29 Kb
├─ file_uploader.bundle.CMC4JLB2.js                         200.53 Kb
├─ file_uploader.bundle.BYQ5LEQA.css                        2.80 Kb
└─ kanban_board.bundle.F72BXL7J.js                          575.41 Kb

press/dist/js/
└─ marketplace.bundle.A5KAQJFZ.js                           17.70 Kb

frappe/dist/css/
├─ desk.bundle.KEJWVG6F.css                                 592.48 Kb
├─ email.bundle.MFPSLI4Q.css                                5.97 Kb
├─ login.bundle.4TZ2WVNK.css                                32.25 Kb
├─ print.bundle.XERKW5TG.css                                203.35 Kb
├─ print_format.bundle.256QGRSA.css                         186.13 Kb
├─ report.bundle.SIMIXBQ4.css                               5.33 Kb
├─ web_form.bundle.QAQFNXDK.css                             14.69 Kb
└─ website.bundle.K5LLMHE4.css                              443.12 Kb

frappe/dist/css-rtl/
├─ desk.bundle.QPKJPL3F.css                                 593.00 Kb
├─ email.bundle.4DC5TLAF.css                                5.98 Kb
├─ login.bundle.F65WFUB5.css                                32.25 Kb
├─ print.bundle.XO3VJ5RF.css                                203.51 Kb
├─ print_format.bundle.IZXAQ6C3.css                         186.26 Kb
├─ report.bundle.X24OJKVV.css                               5.33 Kb
├─ web_form.bundle.3E32ZWTK.css                             14.68 Kb
└─ website.bundle.A4AZRMAK.css                              443.27 Kb

 DONE  Total Build Time: 55.930s

Running build command for press
$ NODE_ENV=production yarn run build-all
$ yarn run build-app && yarn run build-email-css && yarn run build-marketplace-css && yarn run build-saas-css
$ cd dashboard && yarn build
$ yarn generate-theme-config && vite build --base=/assets/press/dashboard/ && yarn copy-html-entry && yarn copy-html-entry2
$ node ./generateThemeConfig.js
vite v4.4.9 building for production...
transforming (7) node_modules/@sentry/vue/esm/index.js[unplugin-vue-components] component "FrappeCloudLogo"(/home/frappe/frappe-cloud/apps/press/dashboard/src/components/icons/FrappeCloudLogo.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "ChangeAppBranchDialog"(/home/frappe/frappe-cloud/apps/press/dashboard/src/components/marketplace/ChangeAppBranchDialog.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "ChangeAppBranchDialog"(/home/frappe/frappe-cloud/apps/press/dashboard/src2/components/bench/ChangeAppBranchDialog.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "Alert"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/Alert.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "Badge"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/Badge.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "Breadcrumbs"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/Breadcrumbs.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "Card"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/Card.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "FileUploader"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/FileUploader.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "Link"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/Link.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "ListItem"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/ListItem.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "Popover"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/Popover.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "Select"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/Select.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "Spinner"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/Spinner.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "Tabs"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/Tabs.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "CommandPalette"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/CommandPalette/CommandPalette.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "FontColor"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/TextEditor/icons/font-color.vue) has naming conflicts with other components, ignored.
[unplugin-vue-components] component "Link"(/home/frappe/frappe-cloud/apps/press/dashboard/node_modules/frappe-ui/src/components/TextEditor/icons/link.vue) has naming conflicts with other components, ignored.
transforming (61) node_modules/frappe-ui/src/components/FileUploader.vueBrowserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
transforming (138) src/views/bench/BenchSettings.vue
Inter-DisplayRegular.woff2?v=3.19 referenced in /home/frappe/frappe-cloud/apps/press/dashboard/src/assets/style.css?vue&type=style&index=0&src=true&lang.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
transforming (621) src/views/general/JobsDetail.vueKilled
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:887:11)
    at execSync (node:child_process:959:15)
    at run_build_command_for_apps (/home/frappe/frappe-cloud/apps/frappe/esbuild/esbuild.js:451:5)
    at execute (/home/frappe/frappe-cloud/apps/frappe/esbuild/esbuild.js:128:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 137,
  signal: null,
  output: [ null, null, null ],
  pid: 6448,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-cloud/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/frappe/frappe-cloud/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-cloud/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-cloud/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-cloud/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-cloud/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-cloud/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-cloud/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/frappe-cloud/apps/frappe/frappe/commands/utils.py", line 72, in build
    bundle(
  File "/home/frappe/frappe-cloud/apps/frappe/frappe/build.py", line 257, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/frappe/frappe-cloud/apps/frappe/frappe/commands/__init__.py", line 97, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --run-build-command' returned non-zero exit status 1.
frappe@cloud:~/frappe-cloud/apps/press$

**Comment by ur-uw** [comment]
Ram Must be greater than 2GB

**Comment by ankush** [comment]
For reference `137` exit code means out-of-memory error.
