### ISSUE TITLE
Docker image build should not block the worker entirely

### ISSUE THREAD

**Issue by ankush** [frappe/press#1238]
Problems:

1. Worker is blocked
2. Worker**S** can't be restarted until that one worker finishes its job.

**Comment by ankush** [comment]
@18alantom since you'll likely be working on deploy. This seems like a major design flaw. Maybe the process should be disowned completely? IDK ideal solution here but something better is required for sure.

**Comment by adityahase** [comment]
With remote builds. This is no longer a problem.

We still block workers on agent. But only builds run on the current build servers.
