### ISSUE TITLE
feat: hotfix patches on running bench

### ISSUE THREAD

**Issue by ankush** [frappe/press#1305]
If I have a private bench and there's urgent fix that needs to be deployed I might wanna skip entire update and apply specific fix. 

This is both good and bad. 

The good: Urgent issues get addressed instantly. 
The bad: sanctity of image representing the exact code that's released is gone. So debugging future issue becomes harder if they are related to applied changes. 

Possible impl:

- A dialog for select app and applying patch. Accept a URL e.g. https://github.com/frappe/press/pull/1302.patch 
- `wget URL -o file && git apply patch file`. This can fail if there are conflicts, bail completely in that case as there's nothing we can do about it. Hotfixes should be small and should be applied on relatively recent code (ideally just 1-2 minor version behind)
- bench restart, bench build to apply changes
- if migrate required then let user do it
- store history of actions and maybe display it somewhere that bench isn't "pure" anymore and has patches applied to it. 
- let users undo patches. `git reset --hard original_hash` and bench build/restart.

Note: This is done on running bench (instance) not on release group or DC or any image.

**Comment by michellealva** [comment]
only on desk
