### ISSUE TITLE
Only show compatible versions while installing app from marketplace

### ISSUE THREAD

**Issue by surajshetty3416** [frappe/press#1325]
https://github.com/frappe/press/assets/13928957/b0ab864f-80cf-45fa-96ed-afb1c7abad38

Here, Frappe Builder is not available in version 14, but I still get "Version 14" option. It should just show "Version 15" & "Nightly" (in that order if possible). 
Also, while specifically installing an app from marketplace, the app should be pre-selected. Currently, the app has to be selected again from the list.

**Comment by BreadGenie** [comment]
closing since the flow is different in the new dashboard
