### ISSUE TITLE
Site getting served from incorrect bench

### ISSUE THREAD

**Issue by ankush** [frappe/press#1366]
This happens randomly but sometimes after migration site is still being served from old container. Not sure what's the problem here.

**Comment by ankush** [comment]
This happens when cross-cluster migrate fails and site is not cleared. Happened just now with me.

**Comment by balamurali27** [comment]
> This happens when cross-cluster migrate fails and site dir is not cleared. Happened just now with me.

This case is fixed with [this](https://github.com/frappe/press/issues/1353).

Need to also do https://github.com/frappe/press/issues/910

**Comment by balamurali27** [comment]
fixed by #1537
