### ISSUE TITLE
Agent: Lock bench nginx conf on generation

### ISSUE THREAD

**Issue by balamurali27** [frappe/press#1369]
Dirty writes happen when 2 sites in same bench update.
Ref ticket no. 8659

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/19133

**Comment by ankush** [comment]
This can still happen https://github.com/frappe/agent/pull/86#discussion_r1519746463 


Lock should be acquired before processing anything and should be closed after processing everything.

**Comment by balamurali27** [comment]
Properly fixed in https://github.com/frappe/agent/commit/3edbed20633da831d7f17880fcc5279867b9dab9
