### ISSUE TITLE
(ux) Filters in Jobs tab could be useful

### ISSUE THREAD

**Issue by vorasmit** [frappe/press#1434]
There are instances where we wish to filter jobs by categories
=> Like when was it updated
=> Failed Jobs

It's currently polluted by Backup Processes and it would enhance ux.

![image](https://github.com/frappe/press/assets/10496564/93bbe967-bcbc-41ca-986f-330f34cd7a39)

**Comment by BreadGenie** [comment]
fixed in new dashboard https://github.com/frappe/press/commit/fd0300e7129dbb9e619ebda6c39c39cf008bde30
