### ISSUE TITLE
UI: odd looking headers with missing values in deploy details

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/press#1436]
![CleanShot 2024-02-13 at 13 03 37@2x](https://github.com/frappe/press/assets/34810212/50a50059-eb07-46db-a107-37d7460e70b7)

Either we can show time elapsed in duration or just a simple "-"...

**Comment by BreadGenie** [comment]
![image](https://github.com/frappe/press/assets/63963181/3debd34c-5bc1-4650-9704-1bcb51c0d6c9)
