### ISSUE TITLE
FIX: some Features are not  displayed in the release group crwation form

### ISSUE THREAD

**Issue by recorner** [frappe/press#1446]
the dependency features not populating 

![image](https://github.com/frappe/press/assets/89336832/f7c33c8b-c2dd-46e6-8978-a3776d812d1b)

the dependencies tab as well 
![image](https://github.com/frappe/press/assets/89336832/5b6d16e3-1b0f-46cb-84be-93bedac00ad0)

am also getting a Server Error
TypeError: 'str' object does not support item assignment when trying to create a release group

**Comment by ankush** [comment]
Seems like something has wrong with migration only. These are just regular forms. See browser console for error.
