### ISSUE TITLE
many UX problems with bench/marketplace apps

### ISSUE THREAD

**Issue by ankush** [frappe/press#1497]
new bench defaults to v13

![image](https://github.com/frappe/press/assets/9079960/6eacb983-29ea-4fcd-b298-5bbe275336d8)

so many pointless apps show up in default list for new bench, have to scroll 2 pages to find "create" button. Just show top 10 apps. 

![image](https://github.com/frappe/press/assets/9079960/689482aa-55e8-44c6-8909-f796104f85ba)

Can't add app that's published in marketplace already. GST India doesn't show up here: https://frappecloud.com/marketplace/apps/gst_india

![image](https://github.com/frappe/press/assets/9079960/167a538d-65c7-4496-90ec-1f05ff138080)

So i go to marketplace URL and install from there

![image](https://github.com/frappe/press/assets/9079960/b58a0175-843b-472a-b9cf-5172a617ac19)

^ here bench should be on left as _usually_ you install apps on bench first. Maybe these two are separate concepts altogether. 

App installed successfully ???

![image](https://github.com/frappe/press/assets/9079960/9916ef8c-8217-4129-8ea9-3247630c812d)

**Comment by surajshetty3416** [comment]
One more: [Only show compatible versions while installing app from marketplace](https://github.com/frappe/press/issues/1325)
