### ISSUE TITLE
Issue while typing the new site name

### ISSUE THREAD

**Issue by NehaSan16** [frappe/press#1547]
When typing the site name, the typing cursor keeps getting disabled (unfocussed). 

<img width="1010" alt="Screenshot 2024-03-13 at 10 25 37 AM" src="https://github.com/frappe/press/assets/139349833/7d027e43-d810-4438-9d50-c901818298ca">
# #

**Comment by BreadGenie** [comment]
8022e42213b9b06deaec8ad928e9f569e6fa6dad
