### ISSUE TITLE
"Add App" related issue

### ISSUE THREAD

**Issue by NehaSan16** [frappe/press#1551]
1. For example, I can see Twilio integration in the list of apps, but unable to find it when I search it. 

<img width="889" alt="Screenshot 2024-03-13 at 11 25 29 AM" src="https://github.com/frappe/press/assets/139349833/d3d22816-ede9-4a08-8e14-418739581af0">

2. Small UX issue, when someone tries to add an app from the marketplace apps, the modal requires users to scroll to the right to see the "Add app" button. Might be a little confusing, especially since scrolling within a modal is not very intuitive.
<img width="894" alt="Screenshot 2024-03-13 at 11 28 55 AM" src="https://github.com/frappe/press/assets/139349833/899e3f5a-ec01-4c49-959e-53a87bb0f36e">

3. when I actually add an app, it is not clear to me if the app got added. I have to close the modal to see that the app has been added to my bench.

4. The app list view seems broken
![Uploading Screenshot 2024-03-13 at 2.08.51 PM.png…]()

**Comment by BreadGenie** [comment]
1. 64c985777662faa1de4ceb0ba9820be6f2a1abbb
2. 25981192c01e4304e07425a0df794c5056349011
3. That is by design. Imagine if a user want to add multiple apps, it would be a chore to open and close the dialog. We can take a look at the design again.
4. The screenshot didn't get uploaded 😅

**Comment by NagariaHussain** [comment]
3. UX Can be improved by showing a tick icon next to app that got installed?

**Comment by BreadGenie** [comment]
3. 9f5d2755ff5c16d7da3890cf9e07b168a089dc9e

**Comment by BreadGenie** [comment]
4. 91cf12b3a3b50e1ca2637b5d2e8d60e14cb8c3fd I'm guessing this should fix the layout
