### ISSUE TITLE
Colour in output breaks logs

### ISSUE THREAD

**Issue by ankush** [frappe/press#1558]
![image](https://github.com/frappe/press/assets/9079960/75088781-27ad-412c-b6bb-925484ed11c7)

possible fix:
- Add NO_COLOR=1 envvar that's respected by most tools
- Add support for colours

**Comment by adityahase** [comment]
Fixed with https://github.com/frappe/agent/commit/f94ac359e43c644fff69f96cafac3800792bc6fe

![image](https://github.com/user-attachments/assets/01188ce3-ae1f-4656-b8f8-bea6c3c434d3)
