### ISSUE TITLE
Incorrect validation error during site creation

### ISSUE THREAD

**Issue by NehaSan16** [frappe/press#1578]
The subdomain is correct and unique, yet the error message shows that I cannot create the site.

<img width="820" alt="Screenshot 2024-03-16 at 12 34 06 AM" src="https://github.com/frappe/press/assets/139349833/1166b60e-ab0b-49f2-8099-fb7224ca3f2c">

**Comment by BreadGenie** [comment]
4be98bdfe1a877d2ecc5c7e3f9716527dc3c9301
