### ISSUE TITLE
UX Issues in the new dashboard - beta

### ISSUE THREAD

**Issue by NehaSan16** [frappe/press#1598]
1. Upgrade site option gives internal server error
<img width="1470" alt="Screenshot 2024-03-19 at 6 26 56 PM" src="https://github.com/frappe/press/assets/139349833/de0fd3dc-66bf-431f-a45c-44437cb93ac3">

2. Transfer site ownership doesn't work 
<img width="1470" alt="Screenshot 2024-03-19 at 6 25 13 PM" src="https://github.com/frappe/press/assets/139349833/ae86b1b3-7280-4651-8c25-6deff54db04b">

3. Error message isn't shown properly when I try to access (download) the backup file
<img width="1470" alt="Screenshot 2024-03-19 at 6 21 51 PM" src="https://github.com/frappe/press/assets/139349833/d0f88bba-4673-4bb3-ac24-ee8031a61b81">

4. App level search doesn't work. When I search for "Raven" it shows random apps but not raven
<img width="1470" alt="Screenshot 2024-03-19 at 5 54 03 PM" src="https://github.com/frappe/press/assets/139349833/6434c8a5-896e-4d67-8ff9-e416bf536709">

5. This pop-up does not close when the database restore file is uploaded and restore is clicked
<img width="1470" alt="Screenshot 2024-03-19 at 6 23 28 PM" src="https://github.com/frappe/press/assets/139349833/66d7ecf5-fa75-49ed-a897-1addac05e9ca">

**Comment by NehaSan16** [comment]
CC: @netchampfaris

**Comment by BreadGenie** [comment]
1. 7a22cc600d7a1bd7b1eebd02900ba38672a2598e
2. 129fbcca8c45556128b514ea88a104fee857649b
3. That error seems to be coming from the site you're taking backup from and not FC
4. WIP
5. 3a3e24b674a9d758a0f193aea912ca9021afd736

**Comment by BreadGenie** [comment]
4. https://github.com/frappe/press/issues/553
