### ISSUE TITLE
When bench is opened, the sites are not visible instantly. They are visible only after you refresh the screen. 

### ISSUE THREAD

**Issue by NehaSan16** [frappe/press#1630]
Refer below screenshot

<img width="1456" alt="Screenshot 2024-03-25 at 3 01 39 PM" src="https://github.com/frappe/press/assets/139349833/b40d19ca-eb89-4a76-a1d7-625fe6d29f30">

**Comment by BreadGenie** [comment]
https://github.com/frappe/press/commit/dea65dc1c8bfc231806080fcd015aa86f2fc0794
