### ISSUE TITLE
managing Streamlit apps in press

### ISSUE THREAD

**Issue by chrigui** [frappe/press#1634]
Hello, 
Is it possible to use press to deploy Streamlit apps for my clients in a metered billing model?

I understand that I must integrate the Streamlit apps with the agent but my question is general at the moment to see if it’s feasible or not.

thanks

**Comment by 18alantom** [comment]
Hi @chrigui unfortunately we don't support any easy way to deploy non Frappe apps, although it something we hope to do in the future.
