### ISSUE TITLE
Doctype Mismatch for Press Dashboard

### ISSUE THREAD

**Issue by malay-gondalia** [frappe/press#1764]
![image](https://github.com/frappe/press/assets/134581231/ff618986-b572-4492-b214-e57d6a762593)

![image](https://github.com/frappe/press/assets/134581231/fd791269-3565-4de6-8408-90ff1afd8a61)

no plan doctype
no Payment Ledger Entry

didn't check all though because i don't know what is linked to which to show on dashboard

![image](https://github.com/frappe/press/assets/134581231/ea6be755-23e6-4a86-9bf0-1eae0399a796)

![image](https://github.com/frappe/press/assets/134581231/06d59c59-4474-49cd-8d5c-0d1262b800fb)

**Comment by shadrak98** [comment]
Probably an old doctype which isn't there anymore. Migrating the site should resolve the issue.
