### ISSUE TITLE
Show app version under Benches > Apps Tab

### ISSUE THREAD

**Issue by 18alantom** [frappe/press#1769]
We rely on app version for validating apps, here's an example:
![image](https://github.com/frappe/press/assets/29507195/eaf2504b-e6be-4318-b155-0362116952cd)

In this case, the user has to guess what version exact version their app is on cause we just show the branch name:
![image](https://github.com/frappe/press/assets/29507195/d37bc98a-5633-433e-aa68-b736497bb075)

This leads to unnecessary support tickets from confused users, who don't understand why their bench can't be updated.

**Comment by BreadGenie** [comment]
9a8988ea5f18bf9d4e1aee6237755bae4965e27a
