### ISSUE TITLE
New Site Creation Failed - Internal Server Error

### ISSUE THREAD

**Issue by NehaSan16** [frappe/press#1789]
Screenshot
<img width="1151" alt="Screenshot 2024-05-20 at 8 58 08 PM" src="https://github.com/frappe/press/assets/139349833/2a8f84b7-6ec7-40b6-b3ac-ae0baf793642">

**Comment by NehaSan16** [comment]
When I tried again, I got this error

<img width="1170" alt="Screenshot 2024-05-20 at 9 00 03 PM" src="https://github.com/frappe/press/assets/139349833/30a5d7d9-5636-4a0b-8d9f-cb0631d5c855">

**Comment by BreadGenie** [comment]
iirc the creation error happened when we were updating prod, closing the issue for now. Open the issue if it happens again.
2nd issue seems like a name collision that has like a very low chance at happening. Maybe we might need to increase the length of the name? @balamurali27
