### ISSUE TITLE
Database Backup file name 

### ISSUE THREAD

**Issue by NehaSan16** [frappe/press#1823]
Hi Team, 

I noted some issues with the file name assigned to the downloaded backup (downloaded a second time) from Frappe Cloud. 

Frappe Cloud assigns it the file name below
<img width="381" alt="Screenshot 2024-05-29 at 1 24 06 PM" src="https://github.com/frappe/press/assets/139349833/89613a59-9945-4e7a-a8e3-cc462bbb7732">

And while restoring, it shows this validation error
<img width="491" alt="Screenshot 2024-05-29 at 1 26 30 PM" src="https://github.com/frappe/press/assets/139349833/db46bd51-dfc6-4ed1-9b22-4b2e822a6106">

Can we please create downloads with compatible names?

**Comment by BreadGenie** [comment]
The file name being weird seems to be the arc browser's tidy downloads feature changing the name
