### ISSUE TITLE
Drop server validation not shown in UI

### ISSUE THREAD

**Issue by balamurali27** [frappe/press#1862]
![image](https://github.com/frappe/press/assets/25403045/aea0672a-4ca3-4d62-b8f5-aa1d1ee66ec6)

@BreadGenie can this be fixed for all such validations?

**Comment by BreadGenie** [comment]
error is shown in toast

<img width="1223" alt="Screenshot 2024-06-13 at 5 39 37 PM" src="https://github.com/frappe/press/assets/63963181/d1de5e12-44e2-425c-a91f-7887eceef979">
