### ISSUE TITLE
Please bring back go to bench 🙏🏼

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/press#1904]
![CleanShot 2024-06-25 at 21 29 27@2x](https://github.com/frappe/press/assets/34810212/d3b5148a-e987-4ba8-b9ec-747dd1deab92)

**Comment by BreadGenie** [comment]
Use breadcrumbs for navigation
One less click as well 🙈

**Comment by NagariaHussain** [comment]
Okay, I don't notice that 🤣
