### ISSUE TITLE
Bug: Cloning the Shared Bench as a Private Bench

### ISSUE THREAD

**Issue by sank8-2** [frappe/press#2183]
This is a major issue.
I had a site on Shared Bench and Decided to move it to Private Bench.
I did not create a Private Bench to transfer the site, and it prompted to Clone the Shared Bench.
On cloning the Shared Bench, there is a glitch that happened with me.
The private bench got created and Unlimited Plans were available.
![image](https://github.com/user-attachments/assets/04bc6111-9829-4f83-8e54-b10202efc9b9)
Then this Bench can be further Cloned for Unlimited access and Unlimited Sites
Please fix this.
Check my site details, if possible, at sanketh.frappe.cloud

**Comment by sank8-2** [comment]
I'm ready to provide help in any way possible.

**Comment by tanmoysrt** [comment]
Hi @sank8-2 , Thanks for reporting the issue.
Can you check, if `Unlimited` plans are still available ?
If not, you can switch to any other available plan.

**Comment by sank8-2** [comment]
Can I get more information about the bug.

**Comment by tanmoysrt** [comment]
> Can I get more information about the bug.

In the `Server` doctype, there is a checkbox `public`. At the time of configuration, tiny bench server was not marked as public and your private bench get created on that. 
Now, the server is marked as `not public`, it assumes that it's a dedicated server and starts showing the `Unlimited Plan`.

**Comment by sank8-2** [comment]
Ok Thanks
