### ISSUE TITLE
Incorrect Currency symbol in list view 

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/press#2243]
![CleanShot 2024-10-31 at 12 38 40@2x](https://github.com/user-attachments/assets/fe764049-4a72-45f7-bf39-9f09622368e0)

> Only if this were true 🤣

**Comment by BreadGenie** [comment]
fixed in https://github.com/frappe/press/commit/1edc2d7656c00fe5c1e24ec9f33eae57560f603b
