### ISSUE TITLE
Deploy Specific Branches on Frappe Cloud

### ISSUE THREAD

**Issue by lsmedev** [frappe/press#2299]
Hi,

I would like to raise a request for an important feature which is to allow us to deploy specific git branches on Frappe Cloud. We use Git Flow where we create a git branch whenever we implement a new feature. It is useful to test the new feature in Dev site before merging the feature branch to main, and before deploying to production.

Currently we are merging the feature branch to main in order to deploy to the dev site, however it is not fully tested and that can break our main branch temporarily, not allowing us to make further updates to production until the feature is fully fixed.

That defeats the purpose of using Git Flow.

Thanks,
Rony

**Comment by nikkothari22** [comment]
@lsmedev Maybe I don't understand the requirement, but isn't this already supported? You can select a branch in your private bench for a specific app. 

Go to your bench group > apps > and then in the three dots beside your app select "Change branch".

<img width="1474" alt="image" src="https://github.com/user-attachments/assets/a45137e5-cbac-4f6c-92dc-ebd2d5eed3eb">

**Comment by lsmedev** [comment]
Oh! This is great then. We had asked frappe cloud support but they told us to create a ticket on the github.
Thanks for clearing this out, we will happily use this feature!
