### ISSUE TITLE
Corrective Job Card Raw Material cost Not Added in the Finished Goods Valuation Cost

### ISSUE THREAD

**Issue by prasathchandrasekar** [frappe/press#2387]
In Manufacturing Some of the Operations has failure and it will require the necessary Corrective Job Card and adding some other material with respective quantity. This Material transaction was not Preplanned and which is only planned by while create the corrective Job Card and Material Transaction. And after Completing Production while transfer the goods from Work in Progress warehouse to Finished goods warehouse, the stock entry does not show the corrective Job card details and also the cost was not added in the finished goods valuation rate.
<img width="746" alt="image" src="https://github.com/user-attachments/assets/d7de7460-4542-4325-8c03-e62075ceb4b5" />
<img width="733" alt="image" src="https://github.com/user-attachments/assets/f346fd37-f614-4d39-a4a8-116baff21dc9" />
<img width="747" alt="image" src="https://github.com/user-attachments/assets/db549053-38b5-4060-a354-dbf352174cc8" />

**Comment by adityahase** [comment]
Wrong repo. Try https://github.com/frappe/erpnext
