### ISSUE TITLE
In COGS system, item group wise GL account required

### ISSUE THREAD

**Issue by sabiha-sh** [frappe/press#2392]
For an example, there are two items :- Color and Chemical (when we talk about textile process house)

Both the items belong to the same warehouse but they have different characteristics and so have different groups.

The person viewing the ledger should have differentiation in GL based on Color and Chemical. He/she would want to see Color consumption separately and chemical consumption separately.

Currently the system allows to have only one GL against the warehouse.

**Comment by adityahase** [comment]
Wrong repo. Please try https://github.com/frappe/erpnext.
