### ISSUE TITLE
app that's not installed on site shows up in update prompt

### ISSUE THREAD

**Issue by ankush** [frappe/press#362]
Ecommerce app isn't installed on this site, still shows up when updating. 

<img width="1352" alt="Screenshot 2022-04-11 at 10 19 22 AM" src="https://user-images.githubusercontent.com/9079960/162666958-b5101ea4-962d-43ec-8bdc-daf5929d2671.png">

**Comment by shadrak98** [comment]
Found a reverted commit https://github.com/frappe/press/commit/63c4e33f80473922aa2622afb7df74feafc58d0c of @NagariaHussain 

Maybe we can add a separate section for new apps on the bench with available updates?

**Comment by ankush** [comment]
@BreadGenie https://github.com/frappe/press/commit/a59b398154fd15b346532e30ddbc06e4465a5407 fixes it?

**Comment by BreadGenie** [comment]
Yep

**Comment by ankush** [comment]
@BreadGenie I am guessing it's because server-side update available logic shouldn't care about apps, can we just hide the not-installed apps in UI? That's a safe change IMO.

**Comment by BreadGenie** [comment]
Ah, the fix will show an empty dialog without the app list when there's a bench update but none of the updates are installed in the site.

**Comment by BreadGenie** [comment]
> @BreadGenie I am guessing it's because server-side update available logic shouldn't care about apps, can we just hide the not-installed apps in UI? That's a safe change IMO.  

yeah, I'll take a look at it

**Comment by BreadGenie** [comment]
#1088
