### ISSUE TITLE
Show commit info for bench apps

### ISSUE THREAD

**Issue by ChillarAnand** [frappe/press#368]
Currently, commit info is displayed for site apps.

<img width="1006" alt="Screenshot 2022-04-21 at 10 59 57" src="https://user-images.githubusercontent.com/4463796/164381052-c44b7ead-3292-4f37-824d-4c1d61c91681.png">

We should do the same for bench apps too so that it would be easy to identify the current commit/state in the bench.

<img width="1006" alt="Screenshot 2022-04-21 at 11 00 07" src="https://user-images.githubusercontent.com/4463796/164381160-daebde19-7059-4dfa-bc46-dc54d0a9f8d7.png">

**Comment by NagariaHussain** [comment]
Since, benches have multiple deployed "Versions", each having different commit information. Hence, we show them separately for each version as Aditya pointed out.

Closing this issue.
