### ISSUE TITLE
bug: page is automatically redirect to site dashboard once site setup is complete.

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/press#421]
I was setting up two new sites, while I was in the process of setting up site B I was redirected to site A dashboard as it had just finished being setup. Lost my progress setting up site B.

**Comment by NagariaHussain** [comment]
Which step were you in? Site creation wizard?

**Comment by dj12djdjs** [comment]
@NagariaHussain I was in the step of uploading site backup. I'm trying to re-create the incident in a screen recording. So far no luck.

**Comment by NagariaHussain** [comment]
Cool, closing this for now.

**Comment by dj12djdjs** [comment]
@NagariaHussain I've been able to replicate this behavior again. Please view the video.
1. Creation of the first site: `0:00` - `0:50`
2. Creation of the second site: `1:06` - `3:07` (Redirection at: `3:00`)

https://screenrec.com/share/dS8MvrIgwQ
