### ISSUE TITLE
Add pre-commit config for auto-formatting + linting

### ISSUE THREAD

**Issue by gavindsouza** [frappe/press#424]
Something similar to how we handle things at frappe/frappe and other apps. Lesser linting & formatting failures in the CI

**Comment by NagariaHussain** [comment]
https://github.com/frappe/press/commit/de7061ec477332d7570d1fa842f6a67835219e6e

**Comment by NagariaHussain** [comment]
Not added to requirement.txt. For setting it up:

1. Install pre-commit package: `pip install pre-commit`
2. Run: `pre-commit install` to setup the pre-commit hook based on the config file

`black` and `flake8` will now run automatically before every commit.
