### ISSUE TITLE
Error when install-app press

### ISSUE THREAD

**Issue by tri-evendi** [frappe/press#437]
**Error when install press in my mac air m1 on local.**
1. Error using dockerfile=3.1.0 in file `frappepress/apps/press/requirements.txt`, just using the latest version will solve this problem in my mac,
2. Error for default value "0" in time() type in file
`.../apps/press/press/press/doctype/deploy_candidate/deploy_candidate.json`
`...{
   "default": "0",
   "fieldname": "build_duration",
   "fieldtype": "Time",
   "label": "Build Duration",
   "read_only": 1
  },...`

3. Column "enable" does not exist in file
`.../apps/press/press/press/doctype/site_config_key_blacklist/site_config_key_blacklist.py`
`if frappe.db.exists("Site Config Key", {"key": self.key, "enabled": True}):`

it's solve by custom or manual edited code, but in this case i think is good for update to the master branch. Thank you.

**Comment by tri-evendi** [comment]
@rutwikhdev ,pls check this issue sir. Thank you.

**Comment by 18alantom** [comment]
Closing this as it may have already been fixed (works on my M1 Mac), local setup reference: https://frappecloud.com/docs/local-fc-setup
