### ISSUE TITLE
Move SaaS billing to respective limits/billing apps

### ISSUE THREAD

**Issue by rutwikhdev** [frappe/press#441]
Every SaaS app will have another app for managing limits and billing. 
`press api` will query these apps on a daily basis to get daily consumption as line items that should be updated on the Invoice

**Comment by rmehta** [comment]
The app can return multiple line-items like

```
[
  {"item": "Support per employee", "unit": "Employee", "rate": 100, "quantity": 10, "amount": 1000},
  {"item": "Statutory filing", "unit": "Fixed", "rate": 300, "amount": 300}
]
```

**Comment by NagariaHussain** [comment]
Maybe press should poll the apps for getting these items periodically.

**Comment by rutwikhdev** [comment]
> Maybe press should poll the apps for getting these items periodically.

Yeah let's poll every 4 or 6 hours and whatever is the maximum line item values for a day will be the total consumption. This solves the problem of people frequently changing plans through out the day.

**Comment by rmehta** [comment]
poll just once at say 2am for the previous day?

**Comment by rutwikhdev** [comment]
> poll just once at say 2am for the previous day?

Yeah not a problem if we restrict downgrades to be from monthly and annual basis.

**Comment by rmehta** [comment]
How does that effect, you will query for the previous day (?)
