### ISSUE TITLE
Invoicing in Frappe Cloud and Frappe.io

### ISSUE THREAD

**Issue by michellealva** [frappe/press#442]
- [x] Create invoices in Frappe Cloud
- [x] Create items in Frappe.io for each app
- [ ] Have add-ons as separate items (only on renewals)
- [x] Include standard hosting with every plan
- [x] Add GST on top of the base plan for Indian customers
- [x] Sync invoices from FC to Frappe.io

**Comment by michellealva** [comment]
@rutwikhdev ETA?

**Comment by rutwikhdev** [comment]
> @rutwikhdev ETA?

Will get to this once the multi-saas workflow is done. Should be done by EOW!
