### ISSUE TITLE
minor annoyance: tag not resolved correctly on apps list

### ISSUE THREAD

**Issue by ankush** [frappe/press#444]
This commit is tagged properly but not recognized on site page (it's automated so can't think of any other reason)

https://github.com/frappe/erpnext/releases/tag/v14.0.1 

dashboard: https://frappecloud.com/dashboard/sites/v14demo.frappe.cloud/overview 

<img width="546" alt="Screenshot 2022-08-22 at 2 38 02 PM" src="https://user-images.githubusercontent.com/9079960/185884297-5fd30df0-b64d-4473-a3ff-288d4809ac5c.png">

**Comment by NagariaHussain** [comment]
It happens the fetching of a tag fails from GitHub (which creates the `Tag` document). Not a UI issue AFAIK.
