### ISSUE TITLE
Site dashboard state is not updated once loaded.

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/press#456]
It seems, a site dashboard keeps it's initial state once it's loaded. It doesn't correspond with the state displayed in "site list view".

**Steps to reproduce**
1. Restore an existing site.
2. Go back to frappe home page (without refreshing page)

**List View**
![image](https://user-images.githubusercontent.com/29856401/187565874-3b639e64-cd43-4803-970d-5664fbecc77a.png)

**Dashboard**
![image](https://user-images.githubusercontent.com/29856401/187565930-51c1708c-d64f-4361-add3-6361f7bba925.png)

**Comment by NagariaHussain** [comment]
Does it show the new state when you refresh the site dashboard page?

**Comment by dj12djdjs** [comment]
@NagariaHussain Yes, it requires a full page reload.

**Comment by NagariaHussain** [comment]
Thanks, I will look into this.
