### ISSUE TITLE
search discoverability in new dashboard

### ISSUE THREAD

**Issue by ankush** [frappe/press#460]
It's beneath the recent site section, not easily discoverable. Totally missed it 👀 

<img width="363" alt="Screenshot 2022-09-01 at 3 38 41 PM" src="https://user-images.githubusercontent.com/9079960/187889483-fb1995b6-3dc1-4d91-85f8-b25cbd62b0ba.png">

**Comment by NagariaHussain** [comment]
Search should be global (nav level) eventually.

**Comment by NagariaHussain** [comment]
Or we should have a "command bar" to do stuff. That would be even cooler. 👨‍💻
