### ISSUE TITLE
Using Frappe fork on private benches

### ISSUE THREAD

**Issue by ankush** [frappe/press#483]
IIRC this was possible before, it's still possible with ERPNext but can't do it for Frappe

am I missing something? 

![telegram-cloud-photo-size-5-6111582486631919934-y](https://user-images.githubusercontent.com/9079960/189110295-2bc18564-c1a8-4fc0-8390-a2f188838733.jpg)

**Comment by NagariaHussain** [comment]
The above error comes because the bench already has the frappe app. The change branch feature should work once FC has access to the fork to create app source.

**Comment by ankush** [comment]
For reference: It's not possible to remove frappe from UI right now.

**Comment by NagariaHussain** [comment]
Intentionally we have prevented these actions from dashboard. Changing branch is also hidden for frappe in dashboard, most of the time it messes things up 😅. 

And not generally used.

**Comment by ankush** [comment]
I agree, feel free to close if no one uses this. The workaround works for me.
