### ISSUE TITLE
Installing Monitoring Server Errror

### ISSUE THREAD

**Issue by Mwogi** [frappe/press#488]
The 3rd last Ansible Task during the setup of the Monitoring Server fails (Configuring Prometheus). See the attached screenshot

![image](https://user-images.githubusercontent.com/736488/189862140-2bdaaf81-64e0-4071-86dc-5612d4cf84ba.png)

Logs:

{
    "diff": [],
    "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_i3ywy7tc/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 653, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_i3ywy7tc/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1187, in set_mode_if_different\n    os.chmod(b_path, mode)\nPermissionError: [Errno 1] Operation not permitted: b'/var/tmp/ansible-tmp-1663059154.9675608-496653-7694749672006/source'\n",
    "exception": "  File \"/tmp/ansible_ansible.legacy.copy_payload_i3ywy7tc/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 653, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_i3ywy7tc/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1187, in set_mode_if_different\n    os.chmod(b_path, mode)\n",
    "invocation": {
        "module_args": {
            "src": "/var/tmp/ansible-tmp-1663059154.9675608-496653-7694749672006/source",
            "dest": "/home/frappe/prometheus/prometheus.yml",
            "force": true,
            "mode": 384,
            "validate": "/home/frappe/prometheus/promtool check config %s",
            "follow": false,
            "_original_basename": "prometheus.yml",
            "checksum": "2210b01631ee999b934a008f65614a069b21077f",
            "backup": false,
            "unsafe_writes": false,
            "content": null,
            "directory_mode": null,
            "remote_src": null,
            "local_follow": null,
            "owner": null,
            "group": null,
            "seuser": null,
            "serole": null,
            "selevel": null,
            "setype": null,
            "attributes": null
        }
    },
    "checksum": "2210b01631ee999b934a008f65614a069b21077f",
    "_ansible_no_log": false,
    "changed": false
}

**Comment by Mwogi** [comment]
@adityahase Any idea what could be causing this? You can point me in a direction and I will see if I can be able to do a pull request.

**Comment by adityahase** [comment]
@Mwogi Could you please provide some more context? Were all other tasks of the `Setup Monitor Server` play completed?

What does the `/home/frappe` directory look like on the monitor server? Try `ls -alh`.

**Comment by Mwogi** [comment]
@adityahase Yes, all the other tasks of the play were completed except this specific task as well as two subsequent tasks that were then skipped because of this error. See below: 
![image](https://user-images.githubusercontent.com/736488/195532135-77379b25-b195-49e3-be4b-13b3169890f5.png)

This is the result for the ls-alh command on the /home/frappe of the monitoring server: 
![image](https://user-images.githubusercontent.com/736488/195532675-e1ad2ac2-aa0b-41aa-8476-a9ac830ab378.png)

**Comment by Mwogi** [comment]
@adityahase I realize that even if I experimentally skip these tasks I encounter multiple other errors later. This happens even when setting up analytics server.

Which operating system platform is recommended for setting up this? I was using Ubuntu 20.04 for this.

**Comment by adityahase** [comment]
We're using Ubuntu 20.04 for local/staging and production environments.

Could you maybe try running the Setup Server action again? I'm sorry but we won't be able to debug this on chat.

**Comment by recorner** [comment]
@ppenter did you find a solution to this problem am having the  same too
