### ISSUE TITLE
Site Activation notice comes even if a site is restored and has already been activated

### ISSUE THREAD

**Issue by aakvatech** [frappe/press#492]
![image](https://user-images.githubusercontent.com/35020381/190548021-2f37b1c3-93a1-49a5-aed2-cdb9e3dfd1e2.png)

Site Activation notice on the top of the site keeps appearing even if the site is already restored with database and files.

**Comment by rutwikhdev** [comment]
Scheduled job for updating this was broken which has been fixed now.
