### ISSUE TITLE
Allow Private Server Option for marketplace app

### ISSUE THREAD

**Issue by bhavesh95863** [frappe/press#501]
Problem:
If we allow all marketplace apps can install private servers then there will be the possibility that users can download the code and use it for a self-hosted server and discuss it with @adityahase  this type of activity we can not stop.

I have a suggestion that we can have an option in the marketplace app that users can select whether this app can install on a private server or not. I think that will be good for developers who want to develop or publish apps but keep that on the private repo.

**Comment by adityahase** [comment]
@bhavesh95863 With the new server-based plans, all sites will be on their own private benches. 

We'll be soon phasing out old plans and public benches.

**Comment by bhavesh95863** [comment]
So you mean there will be only 2 options?
1. Private bench 
2. Server-based plan
