### ISSUE TITLE
Low `max_allowed_packet` in mysqldump.cnf breaks site backup / updates

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/press#527]
The limit is set in `/etc/mysql/conf.d/mysqldump.cnf` in application server. 

**The default for every new server should be at least 256M**, 16M is too low.

@balamurali27

**Comment by ankush** [comment]
https://github.com/frappe/press/blob/2141f55cc5643325cc9c7207a5026816cd4bb103/press/docker/Dockerfile#L103 

🤔

**Comment by NagariaHussain** [comment]
This is not working it seems @ankush

**Comment by adityahase** [comment]
@ankush Tablewise backups are run outside the docker container

https://github.com/frappe/agent/blob/master/agent/site.py#L374-L386

**Comment by ankush** [comment]
Ah simpler then, mysqldump supports passing it as parameter: `--max_allowed_packet=512M`

**Comment by adityahase** [comment]
This is already fixed with https://github.com/frappe/press/commit/9f39a0fedbf64e8215d63cf9e82f4b5dac41c03c
