### ISSUE TITLE
perf: api.bench.versions loads very slow

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/press#533]
It has O(N*M) database queries, where N is the number of non-archived `Benches` for the release group and M is the number of apps in that version.

Check public bench to see the slowness.

Ref: https://frappecloud.com/dashboard/benches/bench-0001/versions

**Comment by ankush** [comment]
https://github.com/frappe/press/commit/ebcb0069fed1e37605051f45dbbfa88e9bdf6c23 

:smile:

**Comment by ankush** [comment]
@balamurali27 checkout https://github.com/frappe/press/pull/628
