### ISSUE TITLE
report for logged deadlocks

### ISSUE THREAD

**Issue by ankush** [frappe/press#548]
Debugging deadlocks without knowing the queries that caused them is next to impossible. 

Currently, we log them but they are on servers and require root access to view. 

Two options:
- Build report to view deadlocks
- Just Ingest in ElasticSearch

Also the table doesn't seem to store all info in `SHOW ENGINE INNODB STATUS`  format which is what central somehow used to do 👀

**Comment by balamurali27** [comment]
Deadlocks are being logged in this database named `percona` in `deadlock` table
