### ISSUE TITLE
ux: Downloading onsite backups shouldn't show forbidden error

### ISSUE THREAD

**Issue by balamurali27** [frappe/press#553]
Right now, if you aren't logged in as user with privileges (to the site) you will get a forbidden error.

Auto-login as admin when attempting to access onsite backups?

**Comment by BreadGenie** [comment]
Have added a message letting them know that they need to be logged in as system user to download backup

![image](https://github.com/user-attachments/assets/a0d82381-e24b-4195-bc27-e282344c6e65)
