### ISSUE TITLE
Unable to limit access to Frappe Cloud based on Roles

### ISSUE THREAD

**Issue by hans-permana** [frappe/press#557]
Hi,

Would it be possible to limit access to Sites/Benches based on role permission? At the moment we have a lot of Private Benches and all the team members (including my developer team) can access all sites as Administrator. This is VERY dangerous!! 

Is there a way to prevent this?

Regards,
Hans

**Comment by rmehta** [comment]
This is an oft requested feature. A simple way to do this is to have 2 levels of users (admin and member)

1. Admins get access to all assets (server, bench, site)
2. Members get access to assets created by them
3. Anyone can "share" their site to other user (explict, like google docs)
4. Members see their sites and sites shared with them.

This seems like an easy fix.

1. Ability to set user type (first user is admin, rest are members - admins can add others as admin)
2. Create a table for shares (use DocShare?) and create a modal to provide share access to members.
3. Filter assets based on type, owner and shared

@rutwikhdev @adityahase

**Comment by ankush** [comment]
tracking here https://github.com/frappe/press/issues/843
