### ISSUE TITLE
the ability to update all sites

### ISSUE THREAD

**Issue by harshit-30** [frappe/press#558]
After updating the bench, it is required to update all the sites too, and doing it manually for 5+ more sites is a tedious task. 
A button or something to update all sites at once would be a good addition to FC.

**Comment by adityahase** [comment]
Added with https://github.com/frappe/press/commit/dd39b1490ec44d5fd0112b1166328fa87136bcbe

**Comment by harshit-30** [comment]
This option only updates the site of one single bench. A bench can have multiple benches. Navigating through active and broken benches to update is again a tedious task.
