### ISSUE TITLE
More information on Bench list

### ISSUE THREAD

**Issue by netchampfaris** [frappe/press#567]
By looking at the Bench list, I should be able to figure out
- update available in one or more apps inside the bench
- deploy in progress

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/9355208/200361007-edf9dd83-6682-4484-a358-edffaf0656af.png">

**Comment by BreadGenie** [comment]
Earlier PR slowed down the fetching lists too much. Will have to optimize how we fetch deploy information.
