### ISSUE TITLE
Set `max_requests` and `max_requests_jitter` in gunicorn to save memory

### ISSUE THREAD

**Issue by ankush** [frappe/press#580]
Workers when they keep running for long time will load many modules in memory and over-time this balloons up a lot. This is because apps load things like excel exporter, pandas etc when "some specific" actions happen, these dont need to live in memory forever and can be reloaded when required.

Gunicorn has config for restarting workers after X requests. 

https://docs.gunicorn.org/en/stable/settings.html#max-requests

We should probably aim to restart ~15-30 minutes?

some numbers to start with;
max_request = 10,000
max_requests_jitter = 1,000

**Comment by rutwikhdev** [comment]
https://github.com/frappe/agent/commit/9ae7e0aa60ead9a998b40be22b3860dfe4ff0f2c
