### ISSUE TITLE
Search option not working in dashboard

### ISSUE THREAD

**Issue by saurabh6790** [frappe/press#586]
<img width="1177" alt="Screenshot 2022-11-16 at 7 53 32 PM" src="https://user-images.githubusercontent.com/3784093/202206012-4b462ee5-92f7-410e-965f-a0a6b73760d8.png">

**Comment by rutwikhdev** [comment]
Seems to work fine for me. Steps to reproduce? BTW you will have to do Impersonate Team on team doc before searching through a particular teams sites. Since the site and bench search only picks up the site's and benches under current active team.
