### ISSUE TITLE
All undelivered jobs are appearing on top for some reason

### ISSUE THREAD

**Issue by ankush** [frappe/press#615]
site > jobs page shows "undelievered" jobs first even if they are not recent, dont think this is intentional.

**Comment by ankush** [comment]
Nope, still an issue.

**Comment by adityahase** [comment]
https://github.com/frappe/press/commit/a3f31914362071eafc6d79e009a21d27791d3b6f

**Comment by ankush** [comment]
https://github.com/frappe/press/pull/1373/commits/f19fa8b5fbbeed7b81e210517d80239485f47063 

This was one of the reason :woozy_face:
