### ISSUE TITLE
Enhance analytics for marketplace apps

### ISSUE THREAD

**Issue by michellealva** [frappe/press#631]
- Total number of active installs
- App-wise activation/usage
- sites installed  - date of installation and date of uninstallation
- in-app contact by app owner to app user (?)

**Comment by rutwikhdev** [comment]
View, payment and install analytics https://github.com/frappe/press/pull/904
We already show a lot of this info in subscriptions tab
![image](https://github.com/frappe/press/assets/50401596/612f7a3c-56dd-499a-bfae-d9fb8bf4d477)
