### ISSUE TITLE
Remove explicit markupsafe install

### ISSUE THREAD

**Issue by ankush** [frappe/press#650]
https://github.com/frappe/press/blob/2141f55cc5643325cc9c7207a5026816cd4bb103/press/docker/Dockerfile#L158

This is incompatible now. Also FC shouldn't be pinning this, pinned it in framework here: https://github.com/frappe/frappe/pull/19348. Looks like it was done because of last packaging snafu with jinja.

**Comment by nk521** [comment]
fix: https://github.com/frappe/press/pull/668
