### ISSUE TITLE
Fund a site user's account

### ISSUE THREAD

**Issue by ukwuezeobinna** [frappe/press#656]
I have Press setup, If a site user does a fund transfer to my local bank, is there a way to add the funds to their wallet/account?

**Comment by NagariaHussain** [comment]
You can create a balance transaction record with the amount.

**Comment by ukwuezeobinna** [comment]
Can you point me to how I can do this? Thanks.

**Comment by NagariaHussain** [comment]
<img width="1619" alt="CleanShot 2023-01-01 at 16 41 18@2x" src="https://user-images.githubusercontent.com/34810212/210168651-aa47af56-6187-480f-9e71-9c34b0bd3520.png">


https://user-images.githubusercontent.com/34810212/210168656-10a4d900-fa6b-481c-ac29-ad0d6e1f4d76.mp4
