### ISSUE TITLE
Change billing currency

### ISSUE THREAD

**Issue by ukwuezeobinna** [frappe/press#657]
A site user's account balance is in a local currency (NGN), is there a way to change it to USD. Where is the currency fetched from?

Note: we have ERPNext installed alongside Press, and changing the default currency does fix this. Is this a bad idea to run Press with ERPNext?

**Comment by NagariaHussain** [comment]
We have made the assumption that there are only two currencies in any case: “INR” and “USD” and a lot of the code depends on it. 

I don’t think you can change the currency that easily, you might have to change the code for invoicing/balance transactions too 😅
