### ISSUE TITLE
possible bug in signup dialog PW verification

### ISSUE THREAD

**Issue by flypenguin** [frappe/press#671]
## Description of the issue

bad password registering dialog on frappecloud.com

## Context information (for bug reports)

i don't know if this is configuration, but it's broken.

## Steps to reproduce the issue

1. open https://frappecloud.com/frappe/signup
2. enter your data, and this password: `!NW4Ucun2^mmxt8SU%bsGd%4`
3. see this error message: "Bad Password! The password length should be atleast 8 characters and it should contain a combination of capital letters, small letters, numbers and symbols"
4. be confused

### Observed result

error message

### Expected result

account signup

## Additional information

firefox, the given URL above

**Comment by shadrak98** [comment]
the password strength checks internally validates for max 20 chars only. extended the limit to 35 chars https://github.com/frappe/press/commit/a43babf98894b3c4d1c82ebd2a55943184856370
