### ISSUE TITLE
Include Tag field for resources

### ISSUE THREAD

**Issue by hari-madhavan** [frappe/press#707]
It would be good to have tag fields for resources ( esp billable resources ). This would enable us to cater to different scenarios in billing - viz. advance paid, paid by customer/us , demo instance etc - through scripted logic

**Comment by hari-madhavan** [comment]
Hi @rutwikhdev , is this deployed on production ? I don't seem to be able to activate the tags

**Comment by rutwikhdev** [comment]
@hari-madhavan it should be updated today or tomorrow

**Comment by hari-madhavan** [comment]
feature is great. A couple of feedback - can we allow deletion of tags and also show them in sorted order in lists - easier to navigate
