### ISSUE TITLE
Create a new site from offsite backup

### ISSUE THREAD

**Issue by adityahase** [frappe/press#719]
Allow creating a new site from an offsite backup (this is already possible from the desk UI).

Should help in 

1. Trying out new versions
1. Making Production -> Staging copies

**Comment by ashish-greycube** [comment]
Whenever , we create new site using upload backup URL from existing site. It fails

> subprocess.CalledProcessError: Command '['tar', 'xvf', '/home/frappe/frappe-bench/sites/amrutenergy14.frappe.cloud/20230125_190808-amrutenergy_frappe_cloud-files.tar', '--strip', '2']' returned non-zero exit status

-------------------------------------------------------
https://frappecloud.com/support/tickets/0348189
https://frappecloud.com/support/tickets/0343744
https://frappecloud.com/support/tickets/0347841

-------------------------------------------------------
Note : we cannot using download on local and then upload option as backups with files are huge ex. 8GB private files, 12 GB public files etc.
We want you to fix this issue as every time we raise it engineer assigned would ask us to try it 2-3 times saying the backup is corrupt which is never the case.

**Comment by balamurali27** [comment]
fixed by 5afb47ab9
