### ISSUE TITLE
Update bench version from 5.15.2 to latest

### ISSUE THREAD

**Issue by ankush** [frappe/press#722]
diff: https://github.com/frappe/bench/compare/v5.15.2...v5.16.1

Main changes:
- Fixes failures where `__version__` is missing in apps -  https://github.com/frappe/bench/pull/1409
- chdir monkey patch is done earlier for clearing command cache - https://github.com/frappe/bench/pull/1421

**Comment by ankush** [comment]
TODO:

- add new one as option in allowed bench versions
- update all internal RGs
- update saas RG
- update public bench RGs
- make it default in code and update all private bench RGs which are untouched.

**Comment by ankush** [comment]
This update is now even more required because of 2 new features: 
- cache in get-app
- validate deps

**Comment by 18alantom** [comment]
Enabled Release Groups on Version 15 and Nightly have been bumped to 5.22.0. They should be using 5.22.0 from the next deploy.

Default bench versions have been set to 5.22.0 in #1430.
