### ISSUE TITLE
Frappe Cloud Server Feature to support  Bring-Your-Own-Cloud (BYOC) 

### ISSUE THREAD

**Issue by pythonpen** [frappe/press#724]
Case is the  Client is a VC startup who managed to get decent aws credits. 

Would be nice if we have ways to bring such accounts on to FC. 

The solution may to enable a Bring-Your-Own-Cloud (BYOC) Feature on FC

**Comment by BreadGenie** [comment]
https://frappecloud.com/docs/hybrid/introduction
