### ISSUE TITLE
db access feature should be read only by default

### ISSUE THREAD

**Issue by ankush** [frappe/press#761]
People execute crazy things without knowing what they are doing. 

This feature is primarily useful for BI tools which don't need write access, maybe we can give read access by default and only enable writes if user opts in for it.

**Comment by adityahase** [comment]
https://github.com/frappe/press/commit/c6e9271d6f985179c048f40e0d18bfa7572c5cb1
https://github.com/frappe/agent/commit/27aae2f75729bcd1bea1d53dec1f024b6aba5905
