### ISSUE TITLE
UX: Customers are unaware of the existence of /dashboard/billing

### ISSUE THREAD

**Issue by balamurali27** [frappe/press#805]
When visiting dashboard page, customer only sees the following:
![image](https://github.com/frappe/press/assets/25403045/b163973e-58e8-437b-a94b-f897ff3cc376)

The blue button takes them to stripe invoice page corresponding to last unpaid invoice directly. Even in cases where there are multiple unpaid invoices. After payment is done, the site is still not active because there are still unpaid invoices from the previous months. This leads them to believe that even after payment is done, they're still being asked to pay.

Ideally, the button should just redirect them to /dashboard/billing where they can see the list of all unpaid invoices and pay from there only.

![image](https://github.com/frappe/press/assets/25403045/4a4d0a34-dac4-4ea7-ae5b-05839540f7c2)

Perhaps the pay now button should not be white. Reconsider ui for this element, maybe. Primary buttons on hover, perhaps.

**Comment by rutwikhdev** [comment]
@BreadGenie We can add a toggle in <template #actions> to (show only)filter unpaid invoices.
