### ISSUE TITLE
Must use AWS and Docker?

### ISSUE THREAD

**Issue by charleslcso** [frappe/press#812]
I think there's no other way to run FC. #724, #622 Must be setup on AWS, Docker. 

We can live with Stripe, and we want the flexibility to run on Chinese cloud for our Mainland clients. 

Anyone can comment on feasibility of not using AWS and not using Docker?

**Comment by ankush** [comment]
Not using docker isn't possible. FC is designed around containers completely. 

Other cloud providers would work but you'll have to fork and modify code here and there. 

There's BYOD feature in works which might make this more flexible

cc: @athul
