### ISSUE TITLE
Some repositories required to be Fetch Latest one at a time and attempt Updating of branch

### ISSUE THREAD

**Issue by aakvatech** [frappe/press#836]
I have two repositories on the fc dashboard:
https://github.com/aakvatech/bulk-Webhook/
and 
https://github.com/aakvatech/Frappe-Permission

main branches, but the Deploy to bench (update bench) keeps failing till "Fetch Latest" is done a few times and then it works

![image](https://github.com/frappe/press/assets/35020381/fb9a85c7-fc4d-4cef-8fab-abe3baed92c1)

**Comment by rutwikhdev** [comment]
Closing as duplicate. Tracked here https://github.com/frappe/press/issues/827
