### ISSUE TITLE
5% of SaaS account requests fail

### ISSUE THREAD

**Issue by ankush** [frappe/press#848]
This is the code that breaks and for unknown reasons, the site isn't allocated to new sign-ups. 

https://github.com/frappe/press/blob/631408244f6271c4637543cf6da078f3b43f488d/press/api/saas.py#L84-L103

You can find this data on posthog.

**Comment by rutwikhdev** [comment]
Mostly account request throttling and spam blocking scripts caused this. And since the first event happens before ```account_request.insert(ignore_permissions=True)``` We are logging false events
