### ISSUE TITLE
Connection Lost,No internet connections for new site

### ISSUE THREAD

**Issue by oderao** [frappe/press#859]
I get a connection lost no internet connection for created via Press

Anyone else had this issue and how did you resolve it?

<img width="364" alt="image" src="https://github.com/frappe/press/assets/34449885/ea567603-7701-4f86-a6d1-073b10ea327b">

**Comment by oderao** [comment]
To fix this set the `developer_mode` to 1 from the press dashboard

setting developer mode may return invalid key so you may have to override the function located at `press.api.config.is_valid`

**Comment by ankush** [comment]
This doesn't have anything to do with press.


When framework detects you don't have internet connection using navgiator.onLine API in browser it shows this message.
