### ISSUE TITLE
Error in `yarn build` should stop the deploy

### ISSUE THREAD

**Issue by netchampfaris** [frappe/press#874]
Even though the "build" command resulted in an error, the deploy continued and sites were updated leading to a broken site.

<img width="707" alt="image" src="https://github.com/frappe/press/assets/9355208/d841ed47-00f2-41d5-b6f8-5cf07b277a31">

**Comment by ankush** [comment]
@netchampfaris most likely framework not returing exit code

https://github.com/frappe/frappe/pull/21084

This this PR present in your update?
