### ISSUE TITLE
deploy and update site component UX

### ISSUE THREAD

**Issue by ankush** [frappe/press#892]
Skip failing patches appears like a site :eyes: 

Not sure best solution here but few options

- Remove checkboxes from site name because the entire card component is selectable. 
- Move "skip failing patch" to side

![image](https://github.com/frappe/press/assets/9079960/dbc6aaf7-a872-49f4-883b-2ca3f3afd596)

**Comment by BreadGenie** [comment]
resolved in new dashboard
![image](https://github.com/frappe/press/assets/63963181/89e45e73-4923-4cc4-823c-46b599831e5d)
