### ISSUE TITLE
Site Backup Failure

### ISSUE THREAD

**Issue by oderao** [frappe/press#912]
All my site backups have been failing
With this error below
NB I created a fresh site and attempted to do a backup and still got the same error.
Anyone has had similar problems??
`b'mysqldump: Got error: 2002: "Can\'t connect to MySQL server on \'10.106.0.3\' (115)" when trying to connect\n'
Backup failed for Site random.mysite.com. Database or site_config.json may be corrupted`

**Comment by BreadGenie** [comment]
Hey, is the issue still persisting?
If it is still persisting can you create a ticket over at https://frappecloud.com/support
