### ISSUE TITLE
worker allocation logic 0.75 too little for 4GB ram servers

### ISSUE THREAD

**Issue by ankush** [frappe/press#917]
https://github.com/frappe/press/blob/0906828a59a38bc0ba0686fbbf027c4e4990a9fd/press/press/doctype/server/server.py#L813-L816

RAM | keep free RAM
-- | --
<4 | 1.5
<8 | 2
\>8 | 3

**Comment by athul** [comment]
If ram is `<8` then 8000*0.75=6000 which is around the same ram kept free

**Comment by ankush** [comment]
@athul the goal was to have easily understood numbers, hence hardcoding free RAM instead of percentage. Mixing both is kinda confusing.
