### ISSUE TITLE
Show button to "Skip and Deploy"

### ISSUE THREAD

**Issue by michellealva** [frappe/press#964]
Site selection is not mandatory but as the list of sites is shown, it feels that site selection is mandatory. 

Show explicitly that site selection is not mandatory via skip and deploy button or something similar.

<img width="1389" alt="image" src="https://github.com/frappe/press/assets/50285544/f60c82c3-0443-4a6e-a6bc-ea5418fb322d">

**Comment by muchai** [comment]
Also, a select all check. We usually have several sites in a single bench, and we have to select each, for cases we want to update all sites.
