### ISSUE TITLE
marketplace - make app publisher name visible somehwere 

### ISSUE THREAD

**Issue by ankush** [frappe/press#979]
Example page: https://frappecloud.com/marketplace/apps/woocommerceconnector

Who published this? whom to contact for more deets? There are links in side bar but the name "libracore" doesn't appear anywhere. 

Example

![image](https://github.com/frappe/press/assets/9079960/f704ff1b-899f-4ae2-a135-1bb1a6a10a82)

**Comment by ankush** [comment]
@rutwikhdev / @BreadGenie very small fix if any of you wanna attempt this.

**Comment by rutwikhdev** [comment]
@ankush We do have this. Publishers need to setup a [publisher profile](https://frappecloud.com/dashboard/marketplace/publisher-profile)

![image](https://github.com/frappe/press/assets/50401596/fcd15236-7c42-4ceb-b2b5-ea8923f2195b)
