### ISSUE TITLE
App not installed on site after adding it to bench

### ISSUE THREAD

**Issue by michellealva** [frappe/press#980]
1. Created a new bench
2. Added an app
3. Deployed the app, also scheduled an update of the site
4. Showed that the app was added to the bench and the site update was successful. However, the app wasn't installed on the site. I then had to again install the app on the site.

This has happened 2-3 times in the past as well. Not sure if this is a genuine issue.

**Comment by rutwikhdev** [comment]
Install App is a separate job it has nothing to do with Bench + Site update. You will have to do it separately. Bench + Site update will only update the Bench and then Site. Bench updates don't know if the update was for app install, uninstall or just code update, everything is treated as a generic update.

**Comment by michellealva** [comment]
So while updating the bench, I chose to update my site as well and it showed me for a new app "first deploy". This kinda gives an impression that the app will be installed on the site too.
